#undef TAPPING_TERM
#define TAPPING_TERM 180

#define QUICK_TAP_TERM 0

#define COMBO_TERM 35

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "KWlwA/ZPxy0p"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 31

#define TAPPING_TERM_PER_KEY
#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 12
#define AUTOMOUSE_THRESHOLD 10
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define AUTOMOUSE_ENABLED_TRACKPAD false
#define AUTOMOUSE_ONESHOT_TRACKBALL false
#define AUTOMOUSE_ONESHOT_TRACKPAD false
#define RGB_MATRIX_STARTUP_SPD 60

#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
